# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a57c027d168f329e31da08aeaee57f97be2419eef1f9774af07659d229cc56bead0a76adafff06ffc31534c1af887c8ca6bfd0a06e9cab2304f035ab1aaf0ea2

test:
  secret_key_base: 9774f6e121b5c029e76c7e74219f5459663a15cb7de7e508d42d67157ff3f9aa4804ea0d380bae6b2cafbcd6074b953bacd0b2d876ab516339712514c3431b18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
